// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Analizadores/Lexer.jflex

// ------------  Paquete e importaciones ------------
package Analizadores; 

import java_cup.runtime.*;
import Funciones.Tokens;
import Funciones.Errores;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\4\22\0\1\5\1\6"+
    "\1\7\5\0\1\10\1\11\2\0\1\12\1\13\1\14"+
    "\1\0\12\15\1\16\1\17\1\20\1\21\1\22\1\0"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\1\37\1\40\1\41"+
    "\1\42\1\31\1\43\1\44\1\45\1\46\1\47\1\31"+
    "\1\50\1\51\1\52\1\53\1\0\1\54\1\0\1\55"+
    "\1\0\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\1\37\1\40\1\41"+
    "\1\42\1\31\1\43\1\44\1\45\1\46\1\47\1\31"+
    "\1\50\1\51\1\52\12\0\1\3\252\0\2\56\115\0"+
    "\1\57\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\16\16"+
    "\1\17\1\20\1\1\1\0\1\16\1\0\1\21\1\0"+
    "\5\16\1\0\5\16\1\0\6\16\1\0\4\16\1\0"+
    "\1\16\1\0\1\22\4\0\1\23\3\16\1\24\1\16"+
    "\1\24\1\16\1\25\3\16\1\0\1\16\1\26\1\16"+
    "\1\27\1\30\1\31\1\27\2\16\1\0\2\32\1\33"+
    "\1\16\1\0\1\16\1\34\1\33\1\0\1\3\1\35"+
    "\2\16\1\0\1\16\1\36\1\37\1\0\1\40\2\16"+
    "\1\0\2\16\1\0\1\41\2\16\1\0\1\16\1\0"+
    "\2\16\1\0\2\16\1\0\1\16\1\0\2\16\1\0"+
    "\1\42\2\43\1\44\1\16\1\44\1\16\1\0\2\16"+
    "\1\0\1\45\1\16\1\0\1\46\1\0\4\16\1\0"+
    "\1\16\1\0\1\16\2\47\2\50\1\16\1\0\2\51"+
    "\1\0\2\16\1\0\1\16\1\0\1\16\1\0\2\52"+
    "\1\53\1\54\1\55\1\54\1\55\1\16\2\0\1\56"+
    "\1\16\1\0\2\57\1\16\1\0\2\60\1\0\2\61"+
    "\2\62\1\0\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\60\0\140\0\220\0\60\0\60"+
    "\0\60\0\60\0\300\0\360\0\60\0\u0120\0\60\0\60"+
    "\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\60\0\60"+
    "\0\u03f0\0\220\0\60\0\u0420\0\60\0\u0450\0\u0480\0\u04b0"+
    "\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630"+
    "\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930"+
    "\0\u0420\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0150\0\u0a20\0\u0a50"+
    "\0\u0a80\0\u0150\0\u0ab0\0\60\0\u0ae0\0\u0b10\0\u0b40\0\u0b70"+
    "\0\u0ba0\0\u0bd0\0\u0c00\0\u0150\0\u0c30\0\u0150\0\u0c60\0\u0150"+
    "\0\60\0\u0c90\0\u0cc0\0\u0cf0\0\u0150\0\60\0\u0150\0\u0d20"+
    "\0\u0d50\0\u0d80\0\u0db0\0\60\0\u0de0\0\u09f0\0\u0150\0\u0e10"+
    "\0\u0e40\0\u0e70\0\u0ea0\0\u0150\0\u0150\0\u0ed0\0\u0150\0\u0f00"+
    "\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u0150\0\u1020\0\u1050"+
    "\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0"+
    "\0\u1200\0\u1230\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u0150\0\u1320"+
    "\0\u1350\0\u0150\0\u1380\0\60\0\u13b0\0\u13e0\0\u1410\0\u1440"+
    "\0\u1470\0\u0150\0\u14a0\0\u14d0\0\u0150\0\u1500\0\u1530\0\u1560"+
    "\0\u1590\0\u15c0\0\u15f0\0\u1620\0\u1650\0\u1680\0\u16b0\0\u16e0"+
    "\0\u0150\0\60\0\u1710\0\u1740\0\u0150\0\60\0\u1770\0\u17a0"+
    "\0\u17d0\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0\0\u0150\0\60"+
    "\0\u0150\0\u0150\0\u0150\0\60\0\60\0\u18f0\0\u1920\0\u1950"+
    "\0\u0150\0\u1980\0\u19b0\0\u0150\0\60\0\u19e0\0\u1a10\0\u0150"+
    "\0\60\0\u1a40\0\u0150\0\60\0\u0150\0\60\0\u1a70\0\60";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\21\1\23\1\24\1\25"+
    "\1\21\1\26\1\27\2\21\1\30\1\31\2\21\1\32"+
    "\1\33\1\34\1\35\1\21\1\36\3\21\1\37\1\40"+
    "\2\2\1\41\60\0\2\5\3\0\53\5\2\42\1\0"+
    "\4\42\1\43\50\42\14\0\1\44\1\13\60\0\1\45"+
    "\47\0\1\46\66\0\1\21\6\0\27\21\2\0\1\21"+
    "\17\0\1\21\6\0\17\21\1\47\7\21\2\0\1\21"+
    "\17\0\1\21\6\0\7\21\1\50\5\21\1\51\11\21"+
    "\2\0\1\21\17\0\1\21\6\0\10\21\1\52\4\21"+
    "\1\53\11\21\2\0\1\21\1\54\16\0\1\21\6\0"+
    "\11\21\1\55\2\21\1\56\7\21\1\57\2\21\2\0"+
    "\1\21\17\0\1\21\6\0\17\21\1\60\7\21\2\0"+
    "\1\21\17\0\1\21\6\0\10\21\1\61\16\21\2\0"+
    "\1\21\1\62\16\0\1\21\6\0\1\63\26\21\2\0"+
    "\1\21\17\0\1\21\6\0\1\64\3\21\1\65\3\21"+
    "\1\66\4\21\1\67\4\21\1\70\4\21\2\0\1\21"+
    "\1\71\16\0\1\21\6\0\17\21\1\72\7\21\2\0"+
    "\1\21\17\0\1\21\6\0\4\21\1\73\22\21\2\0"+
    "\1\21\17\0\1\21\6\0\22\21\1\74\4\21\2\0"+
    "\1\21\17\0\1\21\6\0\10\21\1\75\16\21\2\0"+
    "\1\21\1\76\16\0\1\21\6\0\1\77\26\21\2\0"+
    "\1\21\50\0\1\100\26\0\1\101\42\0\6\102\1\103"+
    "\11\102\1\104\1\102\1\105\35\102\15\0\1\21\6\0"+
    "\17\21\1\106\7\21\2\0\1\21\17\0\1\21\6\0"+
    "\1\107\26\21\2\0\1\21\17\0\1\21\6\0\12\21"+
    "\1\110\1\21\1\111\12\21\2\0\1\21\17\0\1\21"+
    "\6\0\23\21\1\112\3\21\2\0\1\21\17\0\1\21"+
    "\6\0\22\21\1\113\4\21\2\0\1\21\51\0\1\114"+
    "\25\0\1\21\6\0\4\21\1\115\22\21\2\0\1\21"+
    "\17\0\1\21\6\0\3\21\1\116\23\21\2\0\1\21"+
    "\17\0\1\21\6\0\4\21\1\117\22\21\2\0\1\21"+
    "\17\0\1\21\6\0\1\120\26\21\2\0\1\21\17\0"+
    "\1\21\6\0\20\21\1\121\6\21\2\0\1\21\1\0"+
    "\1\122\44\0\1\122\12\0\1\122\15\0\1\21\6\0"+
    "\1\21\1\123\25\21\2\0\1\21\17\0\1\21\6\0"+
    "\24\21\1\124\2\21\2\0\1\21\17\0\1\21\6\0"+
    "\3\21\1\125\23\21\2\0\1\21\17\0\1\21\6\0"+
    "\14\21\1\126\12\21\2\0\1\21\17\0\1\21\6\0"+
    "\3\21\1\127\23\21\2\0\1\21\17\0\1\21\6\0"+
    "\12\21\1\130\14\21\2\0\1\21\42\0\1\131\34\0"+
    "\1\21\6\0\10\21\1\132\4\21\1\133\11\21\2\0"+
    "\1\21\1\134\16\0\1\21\6\0\20\21\1\135\6\21"+
    "\2\0\1\21\1\0\1\136\15\0\1\21\6\0\13\21"+
    "\1\137\13\21\2\0\1\21\17\0\1\21\6\0\21\21"+
    "\1\140\5\21\2\0\1\21\47\0\1\141\27\0\1\21"+
    "\6\0\12\21\1\142\4\21\1\143\7\21\2\0\1\21"+
    "\41\0\1\144\20\0\6\102\1\103\11\102\1\104\45\102"+
    "\1\103\11\102\1\145\1\102\1\146\35\102\6\46\1\0"+
    "\51\46\6\0\1\46\13\0\1\46\52\0\1\21\6\0"+
    "\17\21\1\147\7\21\2\0\1\21\17\0\1\21\6\0"+
    "\22\21\1\150\4\21\2\0\1\21\17\0\1\21\6\0"+
    "\20\21\1\151\6\21\2\0\1\21\1\0\1\152\15\0"+
    "\1\21\6\0\1\21\1\153\25\21\2\0\1\21\17\0"+
    "\1\21\6\0\24\21\1\154\1\155\1\21\2\0\1\21"+
    "\7\0\1\156\7\0\1\21\6\0\27\21\2\0\1\21"+
    "\17\0\1\21\6\0\2\21\1\157\24\21\2\0\1\21"+
    "\17\0\1\21\6\0\16\21\1\160\10\21\2\0\1\21"+
    "\17\0\1\21\6\0\21\21\1\161\5\21\2\0\1\21"+
    "\47\0\1\162\27\0\1\21\6\0\4\21\1\163\22\21"+
    "\2\0\1\21\17\0\1\21\6\0\10\21\1\164\16\21"+
    "\2\0\1\21\1\165\16\0\1\21\6\0\1\166\26\21"+
    "\2\0\1\21\17\0\1\21\6\0\14\21\1\167\12\21"+
    "\2\0\1\21\17\0\1\21\6\0\6\21\1\170\20\21"+
    "\2\0\1\21\42\0\1\171\34\0\1\21\6\0\22\21"+
    "\1\172\4\21\2\0\1\21\50\0\1\173\26\0\1\21"+
    "\6\0\22\21\1\174\4\21\2\0\1\21\17\0\1\21"+
    "\6\0\10\21\1\175\16\21\2\0\1\21\1\176\1\0"+
    "\6\102\1\103\11\102\1\145\37\102\15\0\1\21\6\0"+
    "\13\21\1\177\13\21\2\0\1\21\17\0\1\21\6\0"+
    "\15\21\1\200\11\21\2\0\1\21\43\0\1\201\33\0"+
    "\1\21\6\0\12\21\1\202\14\21\2\0\1\21\44\0"+
    "\1\203\32\0\1\21\6\0\7\21\1\204\17\21\2\0"+
    "\1\21\17\0\1\21\6\0\15\21\1\205\11\21\2\0"+
    "\1\21\43\0\1\206\33\0\1\21\6\0\12\21\1\207"+
    "\14\21\2\0\1\21\17\0\1\21\6\0\1\210\26\21"+
    "\2\0\1\21\26\0\1\211\50\0\1\21\6\0\21\21"+
    "\1\212\5\21\2\0\1\21\17\0\1\21\6\0\17\21"+
    "\1\213\7\21\2\0\1\21\47\0\1\214\27\0\1\21"+
    "\6\0\12\21\1\215\14\21\2\0\1\21\40\0\1\216"+
    "\36\0\1\21\6\0\4\21\1\217\22\21\2\0\1\21"+
    "\17\0\1\21\6\0\1\220\26\21\2\0\1\21\26\0"+
    "\1\221\50\0\1\21\6\0\14\21\1\222\12\21\2\0"+
    "\1\21\17\0\1\21\6\0\12\21\1\223\14\21\2\0"+
    "\1\21\40\0\1\224\36\0\1\21\6\0\4\21\1\225"+
    "\22\21\2\0\1\21\45\0\1\226\31\0\1\21\6\0"+
    "\1\21\1\227\10\21\1\230\3\21\1\231\10\21\2\0"+
    "\1\21\17\0\1\21\6\0\6\21\1\232\20\21\2\0"+
    "\1\21\34\0\1\233\42\0\1\21\6\0\14\21\1\234"+
    "\12\21\2\0\1\21\42\0\1\235\34\0\1\21\6\0"+
    "\1\236\26\21\2\0\1\21\17\0\1\21\6\0\15\21"+
    "\1\237\11\21\2\0\1\21\43\0\1\240\33\0\1\21"+
    "\6\0\20\21\1\241\6\21\2\0\1\21\1\0\1\242"+
    "\15\0\1\21\6\0\14\21\1\243\12\21\2\0\1\21"+
    "\42\0\1\244\34\0\1\21\6\0\4\21\1\245\22\21"+
    "\2\0\1\21\32\0\1\246\70\0\1\247\33\0\1\21"+
    "\6\0\1\250\26\21\2\0\1\21\17\0\1\21\6\0"+
    "\10\21\1\251\16\21\2\0\1\21\1\252\16\0\1\21"+
    "\6\0\10\21\1\253\16\21\2\0\1\21\1\254\16\0"+
    "\1\21\6\0\17\21\1\255\7\21\2\0\1\21\45\0"+
    "\1\256\31\0\1\21\6\0\1\257\26\21\2\0\1\21"+
    "\26\0\1\260\50\0\1\21\6\0\13\21\1\261\13\21"+
    "\2\0\1\21\17\0\1\21\6\0\24\21\1\262\1\263"+
    "\1\21\2\0\1\21\52\0\1\264\1\265\23\0\1\21"+
    "\6\0\26\21\1\266\2\0\1\21\54\0\1\267\37\0"+
    "\1\270\42\0\1\21\6\0\17\21\1\271\7\21\2\0"+
    "\1\21\17\0\1\21\6\0\14\21\1\272\12\21\2\0"+
    "\1\21\42\0\1\273\34\0\1\21\6\0\4\21\1\274"+
    "\22\21\2\0\1\21\32\0\1\275\44\0\1\21\6\0"+
    "\1\276\26\21\2\0\1\21\26\0\1\277\50\0\1\21"+
    "\6\0\1\300\26\21\2\0\1\21\26\0\1\301\76\0"+
    "\1\302\31\0\1\21\6\0\4\21\1\303\22\21\2\0"+
    "\1\21\32\0\1\304\44\0\1\21\6\0\13\21\1\305"+
    "\13\21\2\0\1\21\41\0\1\306\44\0\1\307\72\0"+
    "\1\310\20\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6816];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\4\11\2\1\1\11\1\1\2\11"+
    "\16\1\2\11\1\1\1\0\1\11\1\0\1\11\1\0"+
    "\5\1\1\0\5\1\1\0\6\1\1\0\4\1\1\0"+
    "\1\1\1\0\1\1\4\0\6\1\1\11\5\1\1\0"+
    "\6\1\1\11\2\1\1\0\1\1\1\11\2\1\1\0"+
    "\2\1\1\11\1\0\4\1\1\0\3\1\1\0\3\1"+
    "\1\0\2\1\1\0\3\1\1\0\1\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\1\0\5\1"+
    "\1\11\1\1\1\0\2\1\1\0\2\1\1\0\1\1"+
    "\1\0\4\1\1\0\1\1\1\0\4\1\1\11\1\1"+
    "\1\0\1\1\1\11\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\3\1\2\11\1\1\2\0"+
    "\2\1\1\0\1\1\1\11\1\1\1\0\1\1\1\11"+
    "\1\0\1\1\1\11\1\1\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
Tokens token;
Errores error; 


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error = new Errores("Lexico","El caracter "+ yytext() + " no pertenece al lenguaje.", yyline, yycolumn); Funciones.Instruccion.agregarError(error); 
                    //System.out.println("Error Lexico: " + yytext() + " | Fila:" + yyline + " | Columna: " + yycolumn);
            }
          // fall through
          case 52: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 53: break;
          case 3:
            { 
            }
          // fall through
          case 54: break;
          case 4:
            { token = new Tokens("(", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.PARENTESIS_A, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 5:
            { token = new Tokens(")", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.PARENTESIS_C, yycolumn, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 6:
            { token = new Tokens(",", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 7:
            { token = new Tokens("-", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.GUION, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 8:
            { token = new Tokens(yytext(), "Int", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 9:
            { token = new Tokens(":", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.DOSPUNTOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 10:
            { token = new Tokens(";", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.PUNTOYCOMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 11:
            { token = new Tokens("<", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MENOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 12:
            { token = new Tokens("=", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 13:
            { token = new Tokens(">", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MAYOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 14:
            { token = new Tokens(yytext(), "String", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.ID, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 15:
            { token = new Tokens("[", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.CORCHETE_A, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 16:
            { token = new Tokens("]", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.CORCHETE_C, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 17:
            { token = new Tokens("::", "Simbolo", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.DOBLEDOSPUNTOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 18:
            { token = new Tokens(yytext(), "Double", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.NUMERODECIMAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 19:
            { token = new Tokens("arr", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.ARR, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 20:
            { token = new Tokens("DIV", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.DIV, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 21:
            { token = new Tokens("end", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.END, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 22:
            { token = new Tokens("Max", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MAX, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 23:
            { token = new Tokens("Min", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MIN, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 24:
            { token = new Tokens("MOD", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MOD, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 25:
            { token = new Tokens("MUL", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MUL, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 26:
            { token = new Tokens("RES", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.RES, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 27:
            { token = new Tokens("SUM", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.SUM, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 28:
            { token = new Tokens("var", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.VAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 29:
            { token = new Tokens("char", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.CHAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 30:
            { token = new Tokens("ejeX", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.EJEX, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 31:
            { token = new Tokens("ejeY", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.EJEY, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 32:
            { token = new Tokens("EXEC", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.EXEC, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 33:
            { token = new Tokens("Moda", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MODA, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 34:
            { token = new Tokens("label", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.LABEL, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 35:
            { token = new Tokens("Media", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MEDIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 36:
            { token = new Tokens("print", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.PRINT, yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 37:
            { token = new Tokens("column", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.COLUMN, yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 38:
            { token = new Tokens("double", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.DOUBLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 39:
            { token = new Tokens("titulo", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.TITULO, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 40:
            { token = new Tokens("values", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.VALUES, yycolumn, yyline, yytext());
            }
          // fall through
          case 91: break;
          case 41:
            { token = new Tokens("console", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.CONSOLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 42:
            { token = new Tokens("Mediana", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.MEDIANA, yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 43:
            { token = new Tokens("PROGRAM", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.PROGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 94: break;
          case 44:
            { token = new Tokens("tituloX", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.TITULOX, yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 45:
            { token = new Tokens("tituloY", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.TITULOY, yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 46:
            { token = new Tokens("graphBar", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.GRAPHBAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 97: break;
          case 47:
            { token = new Tokens("graphPie", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.GRAPHPIE, yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 48:
            { token = new Tokens("Varianza", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.VARIANZA, yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 49:
            { token = new Tokens("graphLine", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.GRAPHLINE, yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 50:
            { token = new Tokens("Histogram", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.HISTOGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 101: break;
          case 51:
            { token = new Tokens("END PROGRAM", "Id", yyline, yycolumn); Funciones.Instruccion.agregarTokens(token); return new Symbol(sym.END_PROGRAM, yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
