
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERODECIMAL = 3;
  public static final int DOSPUNTOS = 10;
  public static final int DOBLEDOSPUNTOS = 11;
  public static final int CHAR = 22;
  public static final int PUNTOYCOMA = 13;
  public static final int RES = 27;
  public static final int ENTERO = 2;
  public static final int DOUBLE = 23;
  public static final int CORCHETE_C = 21;
  public static final int CORCHETE_A = 20;
  public static final int GRAPHBAR = 38;
  public static final int TITULOY = 43;
  public static final int TITULOX = 42;
  public static final int END_PROGRAM = 5;
  public static final int EJEY = 41;
  public static final int EJEX = 40;
  public static final int IGUAL = 14;
  public static final int COLUMN = 37;
  public static final int TITULO = 39;
  public static final int DIV = 29;
  public static final int GUION = 19;
  public static final int MIN = 36;
  public static final int ID = 9;
  public static final int MEDIANA = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 4;
  public static final int MUL = 28;
  public static final int COMA = 12;
  public static final int MENOR = 17;
  public static final int MODA = 33;
  public static final int MOD = 30;
  public static final int MAYOR = 18;
  public static final int PARENTESIS_C = 16;
  public static final int PARENTESIS_A = 15;
  public static final int VARIANZA = 34;
  public static final int END = 8;
  public static final int SUM = 26;
  public static final int ARR = 25;
  public static final int MEDIA = 31;
  public static final int EXEC = 44;
  public static final int MAX = 35;
  public static final int VAR = 24;
  public static final int PRINT = 7;
  public static final int CONSOLE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "NUMERODECIMAL",
  "PROGRAM",
  "END_PROGRAM",
  "CONSOLE",
  "PRINT",
  "END",
  "ID",
  "DOSPUNTOS",
  "DOBLEDOSPUNTOS",
  "COMA",
  "PUNTOYCOMA",
  "IGUAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "MENOR",
  "MAYOR",
  "GUION",
  "CORCHETE_A",
  "CORCHETE_C",
  "CHAR",
  "DOUBLE",
  "VAR",
  "ARR",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN",
  "GRAPHBAR",
  "TITULO",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY",
  "EXEC"
  };
}

